import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.160.0/build/three.module.js";
const canvas=document.querySelector("#game-canvas"),startScreen=document.querySelector("#start-screen"),messageScreen=document.querySelector("#message-screen"),startButton=document.querySelector("#start-button"),restartButton=document.querySelector("#restart-button"),healthEl=document.querySelector("#player-health"),staminaEl=document.querySelector("#player-stamina"),bossHealthEl=document.querySelector("#boss-health"),bossStateEl=document.querySelector("#boss-state"),flashEl=document.querySelector("#damage-flash"),toastEl=document.querySelector("#toast");
const scene=new THREE.Scene();scene.background=new THREE.Color(0x101419);scene.fog=new THREE.Fog(0x101419,13,34);const camera=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,80);const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const clock=new THREE.Clock(),keys={},arenaLimit=48;let running=false,gameOver=false,hitStun=0,cameraYaw=0,cameraPitch=.32;const player={mesh:null,weaponPivot:null,weaponBlade:null,rollDirection:new THREE.Vector3(0,0,1),health:100,stamina:100,souls:0,speed:3.7,invulnerable:0,attacking:0,attackCooldown:0,roll:0};const enemy={mesh:null,weaponPivot:null,health:100,attackCooldown:1.6,telegraph:0,attacking:0,hurt:0,dead:false};
queueMicrotask(()=>{
	for(const child of [...scene.children])if(![arenaWorld,townWorld,shopWorld,guildWorld,player.mesh,enemy.mesh].includes(child))arenaWorld.add(child);
	createTown();const townArch=townWorld.children.find(child=>child.type==="Group"&&child.position.z===-12);if(townArch)townArch.position.z=-8.1;for(const building of townWorld.children.filter(child=>child.type==="Group"&&child.position.z===-3)){const roof=building.children.find(child=>child.geometry?.type==="ConeGeometry"&&child.position.y>4);if(roof){roof.geometry.dispose();roof.geometry=new THREE.ConeGeometry(3.2,2.8,4);roof.position.y=4.9}}const townColliders=[...colliders];townColliders.push({minX:-16,maxX:16,minZ:-16,maxZ:-9.35},{minX:-16,maxX:-9.35,minZ:-9.35,maxZ:9.35},{minX:9.35,maxX:16,minZ:-9.35,maxZ:9.35},{minX:-16,maxX:16,minZ:9.35,maxZ:16});
	createInterior(shopWorld,false);const shopColliders=[...colliders];createInterior(guildWorld,true);const guildColliders=[...colliders];
	function createCastle(){
		for(const child of arenaWorld.children)child.traverse(object=>{if(object.isMesh)object.visible=false});
		buildRoot=arenaWorld;const ground=mesh(new THREE.PlaneGeometry(20,68),mat(0x343431));ground.rotation.x=-Math.PI/2;ground.position.set(0,-.04,-18);
		for(let side of[-1,1]){addBox(arenaWorld,side*9.6,4,-18,.8,8,66,0x444642);for(const z of[10,-8,-28,-48]){const tower=mesh(new THREE.CylinderGeometry(1.9,2.2,9,8),mat(0x53534b),arenaWorld);tower.position.set(side*8.4,4.5,z);const roof=mesh(new THREE.ConeGeometry(2.25,2.8,8),mat(0x292d2d),arenaWorld);roof.position.set(side*8.4,10,z)}for(let z of[-3,-22,-43]){const banner=mesh(new THREE.BoxGeometry(.12,2.7,1.25),mat(0x782f2e),arenaWorld);banner.position.set(side*9.13,5,z);const crest=mesh(new THREE.BoxGeometry(.14,.42,.34),mat(0xc39a57,.45),arenaWorld);crest.position.set(side*9.04,5.1,z)}}
		for(const z of[-11,-30]){for(const x of[-6.3,6.3]){addBox(arenaWorld,x,3.6,z,1.1,7.2,1,0x625e53);const capital=mesh(new THREE.BoxGeometry(1.5,.45,1.3),mat(0x81775f),arenaWorld);capital.position.set(x,7.25,z)}addBox(arenaWorld,0,7.6,z,13,.7,1.1,0x706b5d);for(let x=-4.5;x<=4.5;x+=1.5)addBox(arenaWorld,x,2.6,z,.1,5.2,.1,0x393a36)}
		for(const z of[-7,-19,-37]){const strip=mesh(new THREE.PlaneGeometry(8,5),mat(z===-37?0x4d3930:0x474641),arenaWorld);strip.rotation.x=-Math.PI/2;strip.position.set(0,.015,z)}
		const dais=mesh(new THREE.CylinderGeometry(3.5,4,.7,12),mat(0x5a5449),arenaWorld);dais.position.set(0,.32,-47);const throne=mesh(new THREE.BoxGeometry(2.6,3.2,1.1),mat(0x473a33),arenaWorld);throne.position.set(0,2.1,-49);for(const x of[-1.15,1.15]){const finial=mesh(new THREE.ConeGeometry(.28,.9,5),mat(0x927343,.45),arenaWorld);finial.position.set(x,3.9,-49)}
		for(const z of[6,-5,-16,-27,-39])for(const side of[-1,1]){const brazier=new THREE.Group();arenaWorld.add(brazier);brazier.position.set(side*7.5,.0,z);const stem=mesh(new THREE.CylinderGeometry(.16,.26,1.6,7),mat(0x393a36),brazier);stem.position.y=.8;const bowl=mesh(new THREE.CylinderGeometry(.4,.23,.3,8),mat(0x79664a),brazier);bowl.position.y=1.65;const flame=mesh(new THREE.ConeGeometry(.22,.65,6),mat(0xff7938,.4,0xff4214),brazier);flame.position.y=2.08;const fire=new THREE.PointLight(0xdc6233,5,8,2);fire.position.y=2.2;brazier.add(fire)}
		for(const x of[-4.8,4.8]){const sentinel=new THREE.Group();arenaWorld.add(sentinel);sentinel.position.set(x,0,-24);const armor=mesh(new THREE.CapsuleGeometry(.46,.95,5,8),mat(0x343b3b),sentinel);armor.position.y=1.25;const helm=mesh(new THREE.SphereGeometry(.42,8,6),mat(0x51534c),sentinel);helm.position.y=2.25;const spear=mesh(new THREE.CylinderGeometry(.045,.06,3.6,6),mat(0x887b5d),sentinel);spear.position.set(x<0?.55:-.55,1.8,0);spear.rotation.z=x<0?-.12:.12}
		addCollider(-10,-9.25,-52,16);addCollider(9.25,10,-52,16);addCollider(-10,10,15,16);addCollider(-10,10,-52,-51);buildRoot=scene
	}
	colliders.length=0;createCastle();const castleColliders=[...colliders];
	const globalLight=new THREE.HemisphereLight(0xc4c1b6,0x242626,1.35);scene.add(globalLight);const fillLight=new THREE.DirectionalLight(0xffe2ba,1.35);fillLight.position.set(-5,10,7);scene.add(fillLight);
	let gameWon=false,equippedWeapon="wayfarer",bossAwake=false,activeAttack=null,attackHitIndex=0;const weaponOwned={wayfarer:true,ashsteel:false,warden:false};const weaponProfiles={wayfarer:{name:"Wayfarer's Sword",duration:.44,cooldown:.58,reach:2.5,hits:[{at:.48,damage:26}],poses:[{t:0,z:-.95,x:-.15},{t:.46,z:1.1,x:-.55},{t:1,z:-.7,x:0}]},ashsteel:{name:"Ashsteel Twinblade",duration:.54,cooldown:.68,reach:2.7,hits:[{at:.28,damage:18},{at:.72,damage:18}],poses:[{t:0,z:-1.2,x:-.15},{t:.28,z:1.3,x:-.7},{t:.5,z:.7,x:.15},{t:.76,z:-1.3,x:-.65},{t:1,z:-.8,x:0}]},warden:{name:"Warden's Edge",duration:.78,cooldown:.92,reach:3.1,hits:[{at:.72,damage:54}],poses:[{t:0,z:-1.9,x:.1},{t:.4,z:-2.15,x:-1.15},{t:.72,z:1.05,x:1.1},{t:1,z:.2,x:0}]}};const originalReset=resetGame,originalEnd=endGame,originalEnemyUpdate=updateEnemy,originalHudUpdate=updateHud,originalCameraUpdate=updateCamera;
	function equipWeapon(name){if(!weaponOwned[name])return;equippedWeapon=name;const blade=player.weaponBlade;if(blade){blade.geometry.dispose();blade.geometry=new THREE.BoxGeometry(name==="warden"?.23:name==="ashsteel"?.18:.14,name==="warden"?1.35:1.05,name==="warden"?.075:.045);blade.material.color.set(name==="warden"?0xaab0a9:name==="ashsteel"?0x91c2b2:0xc6c8bf);blade.material.emissive.set(name==="ashsteel"?0x17473e:0x000000);blade.material.emissiveIntensity=name==="ashsteel"?.55:0}}
	function setArea(area,spawnX=0,spawnZ=5.5){
		currentArea=area;arenaWorld.visible=area==="castle";townWorld.visible=area==="town";shopWorld.visible=area==="shop";guildWorld.visible=area==="guild";enemy.mesh.visible=area==="castle"&&!enemy.dead;
		player.mesh.position.set(spawnX,0,spawnZ);player.mesh.rotation.set(0,0,0);cameraYaw=0;cameraPitch=.32;
		colliders.splice(0,colliders.length,...(area==="shop"?shopColliders:area==="guild"?guildColliders:area==="town"?townColliders:area==="castle"?castleColliders:[]));
		if(area==="castle"){enemy.mesh.position.set(0,0,-43);enemy.mesh.rotation.set(0,0,0);if(!enemy.dead){enemy.health=100;enemy.attackCooldown=1.6;enemy.telegraph=0;enemy.attacking=0;bossAwake=false}}
		const labels={town:"CINDERWICK · MARKET SQUARE",shop:"IRON & EMBER · FORGE",guild:"WAYFARER'S GUILD · HALL",castle:"BLACKKEEP · OUTER WARD"};document.querySelector("#location-label").textContent=labels[area];document.querySelector("#boss-panel").classList.toggle("hidden",area!=="castle");
		const color=area==="castle"?0x171a1d:area==="town"?0x242725:0x211d19;scene.background=new THREE.Color(color);scene.fog=new THREE.Fog(color,area==="town"?22:18,area==="castle"?72:area==="town"?48:34)
	}
	function actionsForArea(){if(currentArea==="town")return[{x:-5,z:-.45,type:"shop",label:"ENTER IRON & EMBER"},{x:5,z:-.45,type:"guild",label:"ENTER THE WAYFARER'S GUILD"},{x:0,z:-7.15,type:"castle",label:"ENTER BLACKKEEP"}];if(currentArea==="shop"||currentArea==="guild")return[{x:0,z:4.05,type:"exit",label:"RETURN TO CINDERWICK"}];return[{x:0,z:11,type:"exit",label:"RETURN TO CINDERWICK"}]}
	function nearestAction(){const position=player.mesh.position;let nearest=null;for(const action of actionsForArea()){const distance=Math.hypot(position.x-action.x,position.z-action.z);if(distance<2.15&&(!nearest||distance<nearest.distance))nearest={...action,distance}}return nearest}
	function updatePrompt(){nearbyAction=nearestAction();const prompt=document.querySelector("#interaction-prompt");prompt.classList.toggle("hidden",!running||serviceOpen||!nearbyAction);if(nearbyAction)prompt.innerHTML=`<b>E</b> &nbsp;${nearbyAction.label}`}
	function openService(kind){
		serviceOpen=true;document.exitPointerLock?.();const panel=document.querySelector("#service-panel"),title=document.querySelector("#service-title"),eyebrow=document.querySelector("#service-eyebrow"),content=document.querySelector("#service-content");panel.classList.remove("hidden");
		if(kind==="shop"){
			eyebrow.textContent="IRON & EMBER · WEAPONSMITH";title.textContent="Choose your steel";
			const weaponCard=(key,cost,description)=>`<div class="service-item"><div>${weaponProfiles[key].name}<small>${description}</small></div>${weaponOwned[key]?`<button data-equip="${key}">${equippedWeapon===key?"EQUIPPED":"EQUIP"}</button>`:`<button data-buy="${key}" data-cost="${cost}">${cost} SOULS</button>`}</div>`;
			content.innerHTML=`<p>Souls: <b>${player.souls}</b> · Equipped: <b>${weaponProfiles[equippedWeapon].name}</b></p><div class="service-list">${weaponCard("wayfarer",0,"Single measured diagonal sweep")}${weaponCard("ashsteel",75,"Fast two-hit crosscut")}${weaponCard("warden",160,"Slow, long-reach overhead cleave")}<div class="service-item"><div>Field draught<small>Restore 35 vitality</small></div><button data-buy="draught" data-cost="30">30 SOULS</button></div></div>`
		}else{
			eyebrow.textContent="WAYFARER'S GUILD · CONTRACT BOARD";title.textContent=questComplete?"A debt repaid":"The Blackkeep contract";
			content.innerHTML=questComplete?"<p>The Ash Warden is fallen. Blackkeep is quiet again.</p>":questAccepted?"<p>Contract active: cross the outer ward and great hall, then defeat the Ash Warden in the throne keep.</p>":"<p>The Ash Warden has sealed Blackkeep. Cross the outer ward and great hall, then defeat it in the throne keep. Reward: 150 souls.</p><div class=\"service-list\"><div class=\"service-item\"><div>Blackkeep contract<small>Claim the throne room</small></div><button id=\"accept-contract\">ACCEPT</button></div></div>"
		}
		updatePrompt()
	}
	function enterAction(action){if(action.type==="shop"){setArea("shop",0,3.7);openService("shop")}else if(action.type==="guild"){setArea("guild",0,3.7);openService("guild")}else if(action.type==="castle"){if(!questAccepted&&!questComplete){showToast("ACCEPT THE GUILD CONTRACT FIRST");return}gameWon=false;setArea("castle",0,8.5);showToast("BLACKKEEP'S GATES CLOSE BEHIND YOU")}else if(action.type==="exit"){setArea("town",currentArea==="shop"?-5:currentArea==="guild"?5:0,currentArea==="castle"?10:-.35)}}
	function interact(){if(serviceOpen)return;nearbyAction=nearestAction();if(nearbyAction)enterAction(nearbyAction)}
	function isBlocked(x,z){return colliders.some(box=>x+.42>box.minX&&x-.42<box.maxX&&z+.42>box.minZ&&z-.42<box.maxZ)}
	function resolveMovement(origin){const next=player.mesh.position;if(!isBlocked(next.x,next.z))return;const canX=!isBlocked(next.x,origin.z),canZ=!isBlocked(origin.x,next.z);if(canX){next.z=origin.z;return}if(canZ){next.x=origin.x;return}next.x=origin.x;next.z=origin.z}
	function buyItem(button){const cost=Number(button.dataset.cost),item=button.dataset.buy;if(player.souls<cost){showToast("NOT ENOUGH SOULS");return}player.souls-=cost;if(item==="draught"){player.health=Math.min(100,player.health+35);showToast("VITALITY RESTORED")}else{weaponOwned[item]=true;equipWeapon(item);showToast(`${weaponProfiles[item].name.toUpperCase()} EQUIPPED`)}openService("shop")}
	setArea("town",0,5.5);enemy.mesh.visible=false;player.souls=120;running=false;gameWon=false;
	resetGame=function(){if(gameWon){gameWon=false;gameOver=false;running=true;messageScreen.classList.add("hidden");setArea("town",0,-7.15);serviceOpen=false;return}originalReset();gameWon=false;questAccepted=false;questComplete=false;weaponOwned.ashsteel=false;weaponOwned.warden=false;equipWeapon("wayfarer");player.souls=120;bossAwake=false;running=true;gameOver=false;setArea("town",0,5.5);document.querySelector("#service-panel").classList.add("hidden");serviceOpen=false};
	endGame=function(won){gameWon=won;if(won&&questAccepted&&!questComplete){questComplete=true;player.souls+=150}originalEnd(won);if(won){document.querySelector("#message-copy").textContent="Blackkeep is yours. The road back to Cinderwick is open.";document.querySelector("#restart-button").innerHTML="RETURN TO CINDERWICK <span>↗</span>"}};
	roll=function(){if(!running||player.stamina<27||player.roll>0||player.attacking>0)return;const direction=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(direction.lengthSq())direction.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),cameraYaw);else direction.set(0,0,1).applyAxisAngle(new THREE.Vector3(0,1,0),cameraYaw);player.rollDirection.copy(direction);player.stamina-=27;player.roll=.52;player.invulnerable=.58};
	strike=function(){if(!running||gameOver||currentArea!=="castle"||!bossAwake||enemy.dead||player.attackCooldown>0||player.roll>0||player.attacking>0)return;const direction=enemy.mesh.position.clone().sub(player.mesh.position);direction.y=0;if(direction.lengthSq())player.mesh.rotation.y=Math.atan2(direction.x,direction.z);activeAttack=weaponProfiles[equippedWeapon];attackHitIndex=0;player.attacking=activeAttack.duration;player.attackCooldown=activeAttack.cooldown};
	updatePlayer=function(delta){
		if(serviceOpen)return;if(player.invulnerable>0)player.invulnerable-=delta;if(player.attackCooldown>0)player.attackCooldown-=delta;if(hitStun>0)hitStun-=delta;
		const origin=player.mesh.position.clone();if(player.roll>0){player.roll=Math.max(0,player.roll-delta);player.mesh.position.addScaledVector(player.rollDirection,delta*9);player.mesh.rotation.y=Math.atan2(player.rollDirection.x,player.rollDirection.z)}else if(hitStun<=0&&player.attacking<=0){const input=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(input.lengthSq()){input.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),cameraYaw);player.mesh.position.addScaledVector(input,delta*player.speed);player.mesh.rotation.y=Math.atan2(input.x,input.z)}}
		if(player.attacking>0&&activeAttack){player.attacking=Math.max(0,player.attacking-delta);const progress=1-player.attacking/activeAttack.duration;while(attackHitIndex<activeAttack.hits.length&&progress>=activeAttack.hits[attackHitIndex].at){const hit=activeAttack.hits[attackHitIndex++];if(!enemy.dead&&player.mesh.position.distanceTo(enemy.mesh.position)<activeAttack.reach){enemy.health=Math.max(0,enemy.health-hit.damage);player.souls+=hit.damage;showToast(activeAttack.hits.length>1?"CROSSCUT CONNECTS":"A CLEAN STRIKE");if(enemy.health<=0){enemy.dead=true;player.souls+=974;setTimeout(()=>endGame(true),650)}}}
			const poseList=activeAttack.poses;let nextPose=poseList.findIndex(pose=>pose.t>=progress);if(nextPose<0)nextPose=poseList.length-1;const previousPose=Math.max(0,nextPose-1),from=poseList[previousPose],to=poseList[nextPose],blend=to.t===from.t?0:THREE.MathUtils.clamp((progress-from.t)/(to.t-from.t),0,1);player.weaponPivot.rotation.z=THREE.MathUtils.lerp(from.z,to.z,blend);player.weaponPivot.rotation.x=THREE.MathUtils.lerp(from.x,to.x,blend);if(player.attacking===0){activeAttack=null;player.weaponPivot.rotation.set(0,0,0)}}
		player.stamina=Math.min(100,player.stamina+delta*(player.roll>0?5:19));resolveMovement(origin);
		if(currentArea==="castle"){player.mesh.position.x=THREE.MathUtils.clamp(player.mesh.position.x,-8.7,8.7);player.mesh.position.z=THREE.MathUtils.clamp(player.mesh.position.z,-49.5,14);if(!bossAwake&&player.mesh.position.z<-30){bossAwake=true;bossStateEl.textContent="AWAKENED";showToast("THE WARDEN RISES IN THE THRONE KEEP")}}
	};
	updateEnemy=function(delta){if(currentArea!=="castle"||!bossAwake)return;const facing=enemy.mesh.rotation.y,wasAttacking=enemy.attacking>0;originalEnemyUpdate(delta);if(wasAttacking)enemy.mesh.rotation.y=facing;if(enemy.weaponPivot){const progress=enemy.attacking>0?1-enemy.attacking/.5:0;enemy.weaponPivot.rotation.z=enemy.attacking>0?Math.sin(progress*Math.PI)*1.65:0;if(enemy.attacking<=0)enemy.weaponPivot.rotation.z=0}};
	updateCamera=function(delta){
		const interior=currentArea==="shop"||currentArea==="guild",target=player.mesh.position.clone();target.y+=1.25;
		const distance=interior?4.1:8.2,height=interior?2.3:4.1+cameraPitch,desired=target.clone().add(new THREE.Vector3(Math.sin(cameraYaw)*distance,height,Math.cos(cameraYaw)*distance));
		if(interior){const direction=desired.clone().sub(target),raycaster=new THREE.Raycaster(target,direction.clone().normalize(),.2,direction.length()),root=currentArea==="shop"?shopWorld:guildWorld,obstruction=raycaster.intersectObjects(root.children,true)[0];if(obstruction)desired.copy(target).addScaledVector(direction.normalize(),Math.max(.45,obstruction.distance-.25));desired.x=THREE.MathUtils.clamp(desired.x,-4.3,4.3);desired.z=THREE.MathUtils.clamp(desired.z,-4.3,4.3);desired.y=THREE.MathUtils.clamp(desired.y,.55,2.7)}
		else if(currentArea==="castle"){desired.x=THREE.MathUtils.clamp(desired.x,-9,9);desired.z=THREE.MathUtils.clamp(desired.z,-51,15)}
		else{desired.x=THREE.MathUtils.clamp(desired.x,-15.2,15.2);desired.z=THREE.MathUtils.clamp(desired.z,-15.2,15.2)}
		camera.position.lerp(desired,1-Math.pow(.001,delta));
		if(interior){camera.position.x=THREE.MathUtils.clamp(camera.position.x,-4.3,4.3);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-4.3,4.3);camera.position.y=THREE.MathUtils.clamp(camera.position.y,.55,2.7)}
		else if(currentArea==="castle"){camera.position.x=THREE.MathUtils.clamp(camera.position.x,-9,9);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-51,15)}
		else{camera.position.x=THREE.MathUtils.clamp(camera.position.x,-15.2,15.2);camera.position.z=THREE.MathUtils.clamp(camera.position.z,-15.2,15.2)}
		camera.lookAt(target)
	};
	updateHud=function(){originalHudUpdate();if(currentArea==="castle"){const z=player.mesh.position.z;document.querySelector("#location-label").textContent=z>-12?"BLACKKEEP · OUTER WARD":z>-30?"BLACKKEEP · GREAT HALL":"BLACKKEEP · THRONE KEEP";if(!bossAwake)bossStateEl.textContent="DORMANT"}updatePrompt()};
	restartButton.addEventListener("click",()=>{restartButton.innerHTML="TRY AGAIN <span>↻</span>"});
	document.querySelector("#service-close").addEventListener("click",()=>{serviceOpen=false;document.querySelector("#service-panel").classList.add("hidden");updatePrompt();canvas.requestPointerLock?.()});
	document.querySelector("#service-panel").addEventListener("click",event=>{const button=event.target.closest("button");if(!button)return;if(button.dataset.buy)buyItem(button);if(button.dataset.equip){equipWeapon(button.dataset.equip);showToast(`${weaponProfiles[equippedWeapon].name.toUpperCase()} EQUIPPED`);openService("shop")}if(button.id==="accept-contract"){questAccepted=true;showToast("CONTRACT ACCEPTED");openService("guild")}});
	addEventListener("keydown",event=>{if(event.code==="KeyE"&&!event.repeat){event.preventDefault();if(serviceOpen){serviceOpen=false;document.querySelector("#service-panel").classList.add("hidden")}else interact()}});
});
const arenaWorld=new THREE.Group(),townWorld=new THREE.Group(),shopWorld=new THREE.Group(),guildWorld=new THREE.Group();scene.add(arenaWorld,townWorld,shopWorld,guildWorld);let buildRoot=scene,currentArea="town",nearbyAction=null,serviceOpen=false,questAccepted=false,questComplete=false;const colliders=[];let collisionTarget=colliders;
function addCollider(minX,maxX,minZ,maxZ){collisionTarget.push({minX,maxX,minZ,maxZ})}
function addBox(parent,x,y,z,width,height,depth,color,roughness=.8){const item=mesh(new THREE.BoxGeometry(width,height,depth),mat(color,roughness),parent);item.position.set(x,y,z);return item}
function mat(color,roughness=.8,emissive=0){return new THREE.MeshStandardMaterial({color,roughness,emissive,emissiveIntensity:emissive?1.5:0})}function mesh(geometry,material,parent=buildRoot){const item=new THREE.Mesh(geometry,material);item.castShadow=true;item.receiveShadow=true;parent.add(item);return item}
function createTown(){buildRoot=townWorld;const ground=mesh(new THREE.PlaneGeometry(32,32),mat(0x45433b));ground.rotation.x=-Math.PI/2;ground.position.y=-.04;const road=mesh(new THREE.PlaneGeometry(5,32),mat(0x292c2a));road.rotation.x=-Math.PI/2;road.position.y=-.01;const crossroad=mesh(new THREE.PlaneGeometry(32,4),mat(0x292c2a));crossroad.rotation.x=-Math.PI/2;crossroad.position.y=-.005;const plaza=mesh(new THREE.CylinderGeometry(2.5,2.8,.22,12),mat(0x77715f));plaza.position.set(0,.08,0);const basin=mesh(new THREE.CylinderGeometry(.9,1.1,.65,12),mat(0x414c49));basin.position.set(0,.48,0);const water=mesh(new THREE.CylinderGeometry(.76,.76,.08,16),mat(0x6e9690,.2,0x203b36));water.position.set(0,.84,0);
for(const [x,label,color] of [[-5,"IRON & EMBER",0x674936],[5,"WAYFARER'S GUILD",0x485246]]){const building=new THREE.Group();townWorld.add(building);building.position.set(x,0,-3);addBox(building,0,1.6,0,4.2,3.2,3.5,color);addBox(building,0,3.35,0,4.7,.45,3.9,0x292b28);const roof=mesh(new THREE.ConeGeometry(3.2,2.1,4),mat(0x35312c),building);roof.position.set(0,4.55,0);roof.rotation.y=Math.PI/4;addBox(building,0,1.6,1.78,1.05,2,.12,0x201f1b);addBox(building,0,3.05,1.86,3.5,.42,.13,0x211e19);const sign=mesh(new THREE.BoxGeometry(2.65,.36,.12),mat(label.includes("IRON")?0x9b6038:0x727648),building);sign.position.set(0,2.93,1.96);const signText=document.createElement("canvas");signText.width=512;signText.height=96;const ctx=signText.getContext("2d");ctx.fillStyle="#ead9b8";ctx.font="bold 42px Georgia";ctx.textAlign="center";ctx.fillText(label,256,62);const texture=new THREE.CanvasTexture(signText);const lettering=mesh(new THREE.PlaneGeometry(2.4,.31),new THREE.MeshBasicMaterial({map:texture,transparent:true}),building);lettering.position.set(0,2.93,2.04);addCollider(x-2.2,x+2.2,-5.1,-1.1)}
for(let i=0;i<8;i++){const angle=i*Math.PI/4,post=mesh(new THREE.CylinderGeometry(.12,.18,2.1,6),mat(0x514638),townWorld);post.position.set(Math.cos(angle)*10,1,Math.sin(angle)*10);const lamp=mesh(new THREE.SphereGeometry(.22,8,6),mat(0xf4a15d,.4,0xd16a31),townWorld);lamp.position.set(Math.cos(angle)*10,2.18,Math.sin(angle)*10)}
const arch=new THREE.Group();townWorld.add(arch);arch.position.set(0,0,-12);addBox(arch,-2.2,2.4,0,.55,4.8,.6,0x4a463e);addBox(arch,2.2,2.4,0,.55,4.8,.6,0x4a463e);addBox(arch,0,4.7,0,4.9,.55,.7,0x625343);addBox(arch,0,.12,0,4.4,.2,.9,0x786548);addCollider(-16,16,-16,-15);addCollider(-16,-15,-16,16);addCollider(15,16,-16,16);buildRoot=scene}
function createInterior(root,isGuild){buildRoot=root;const floor=mesh(new THREE.PlaneGeometry(10,10),mat(isGuild?0x50483a:0x4c4036));floor.rotation.x=-Math.PI/2;floor.position.y=-.06;for(const [x,z,w,d] of [[0,-5,10,.3],[-5,0,.3,10],[5,0,.3,10],[-2.6,5,.8,.3],[2.6,5,.8,.3]])addBox(root,x,1.5,z,w,3,d,0x39342d);addBox(root,0,2.95,0,9.8,.25,9.8,0x332e28);
if(isGuild){for(let i=0;i<3;i++){addBox(root,-2.8+i*2.8,1.05,-2.3,2.15,1.8,.65,0x554332);addBox(root,-2.8+i*2.8,2.15,-2.3,1.8,.08,.48,0x98784b)}addBox(root,0,1.1,-3.9,3.8,1.6,.45,0x473a2b);addBox(root,0,2.05,-3.9,4.2,.2,.55,0xa1814d)}else{for(let i=0;i<3;i++){const blade=mesh(new THREE.BoxGeometry(.1,1.4,.12),mat(i===1?0xc4c8bc:0x989d96,.25),root);blade.position.set(-2.8+i*2.8,1.35,-2.5);blade.rotation.z=(i-1)*.35;addBox(root,-2.8+i*2.8,.62,-2.5,.55,.12,.35,0x684a35)}addBox(root,0,.55,-3,2,.85,1,0x4b3527);addBox(root,0,1.06,-3,2.3,.16,1.2,0x76563b)}
colliders.length=0;addCollider(-5.2,-4.65,-5,5);addCollider(4.65,5.2,-5,5);addCollider(-4.65,4.65,-5.2,-4.65);addCollider(-4.65,-.8,4.65,5.2);addCollider(.8,4.65,4.65,5.2);buildRoot=scene}
function createWorld(){scene.add(new THREE.HemisphereLight(0x9c9c9a,0x1a2022,1.2));const moon=new THREE.DirectionalLight(0xe5d9c0,2.1);moon.position.set(-7,12,5);moon.castShadow=true;moon.shadow.mapSize.set(2048,2048);moon.shadow.camera.left=-18;moon.shadow.camera.right=18;moon.shadow.camera.top=18;moon.shadow.camera.bottom=-18;scene.add(moon);const fire=new THREE.PointLight(0xdc5f30,20,12,2);fire.position.set(0,1.3,-1.2);scene.add(fire);const ground=mesh(new THREE.CylinderGeometry(11,12,.35,64),mat(0x252a2b));ground.position.y=-.2;const inner=mesh(new THREE.CylinderGeometry(9.7,9.7,.06,64),mat(0x363a36));inner.position.y=.02;for(let i=0;i<24;i++){const angle=i/24*Math.PI*2,radius=10.8+(i%3)*.55,stone=mesh(new THREE.DodecahedronGeometry(.5+(i%4)*.12,0),mat(i%2?0x303432:0x454744));stone.position.set(Math.cos(angle)*radius,.3,Math.sin(angle)*radius);stone.scale.y=.6+(i%3)*.25;stone.rotation.y=angle}for(let i=0;i<16;i++){const angle=i*2.4,radius=7.2+(i%3)*.7,pillar=mesh(new THREE.CylinderGeometry(.22,.38,1.2+(i%4)*.35,6),mat(0x555550));pillar.position.set(Math.cos(angle)*radius,.62,Math.sin(angle)*radius);pillar.rotation.y=angle}const gate=new THREE.Group();scene.add(gate);gate.position.set(0,0,-10.5);for(const x of[-2.3,2.3]){const post=mesh(new THREE.BoxGeometry(.7,5.7,.7),mat(0x353938),gate);post.position.x=x;post.position.y=2.65}const lintel=mesh(new THREE.BoxGeometry(5.3,.75,.8),mat(0x484a43),gate);lintel.position.y=5.25;for(let i=0;i<8;i++){const flame=mesh(new THREE.ConeGeometry(.12+Math.random()*.1,.4+Math.random()*.25,5),mat(0xff8a40,.4,0xff4c12),gate);flame.position.set(-2.3+i*.65,5.65+Math.random()*.15,.05)}for(let i=0;i<55;i++){const ember=mesh(new THREE.SphereGeometry(.025+Math.random()*.035,4,4),mat(0xf17a3e,.5,0xe04c1d));ember.position.set((Math.random()-.5)*20,.3+Math.random()*5,(Math.random()-.5)*18-1)}}
function createPlayer(){
	const group=new THREE.Group();scene.add(group);
	const cloak=mesh(new THREE.ConeGeometry(.68,1.65,7),mat(0x20292b),group);cloak.position.set(0,.95,-.2);cloak.rotation.x=Math.PI;
	const tunic=mesh(new THREE.CapsuleGeometry(.4,.72,5,9),mat(0x39494b),group);tunic.position.y=1.33;
	const cuirass=mesh(new THREE.SphereGeometry(.43,10,8),mat(0x66716b,.42),group);cuirass.position.set(0,1.55,.18);cuirass.scale.set(1,.88,.48);
	const chestStrap=mesh(new THREE.BoxGeometry(.11,1.05,.12),mat(0x684b35),group);chestStrap.position.set(.04,1.34,.42);chestStrap.rotation.z=-.35;
	const belt=mesh(new THREE.BoxGeometry(.76,.14,.48),mat(0x694a32),group);belt.position.set(0,.98,0);
	const buckle=mesh(new THREE.BoxGeometry(.17,.18,.08),mat(0xc29a55,.35),group);buckle.position.set(0,.98,.27);
	for(const side of[-1,1]){
		const leg=mesh(new THREE.CapsuleGeometry(.16,.62,4,7),mat(side<0?0x303b3d:0x354143),group);leg.position.set(side*.2,.53,0);
		const boot=mesh(new THREE.BoxGeometry(.31,.27,.48),mat(0x292724),group);boot.position.set(side*.2,.17,.08);
		const shoulder=mesh(new THREE.SphereGeometry(.3,8,6),mat(0x73776d,.5),group);shoulder.position.set(side*.47,1.72,-.02);shoulder.scale.set(1,.72,.92);
		const arm=mesh(new THREE.CapsuleGeometry(.13,.46,4,7),mat(0x596361),group);arm.position.set(side*.48,1.37,.02);arm.rotation.z=-side*.12;
		const vambrace=mesh(new THREE.BoxGeometry(.25,.32,.25),mat(0x77796f,.45),group);vambrace.position.set(side*.5,1.16,.06);
	}
	const head=mesh(new THREE.SphereGeometry(.29,12,9),mat(0xa78069),group);head.position.set(0,2.08,-.02);head.scale.set(.92,1.05,.9);
	const hood=mesh(new THREE.SphereGeometry(.35,10,7),mat(0x283234),group);hood.position.set(0,2.21,.08);hood.scale.set(1,.88,.88);
	const brow=mesh(new THREE.BoxGeometry(.45,.16,.38),mat(0x72766e,.42),group);brow.position.set(0,2.26,.2);
	const visor=mesh(new THREE.BoxGeometry(.34,.1,.04),mat(0xd9874e,.3,0x63290f),group);visor.position.set(0,2.14,.326);
	const crest=mesh(new THREE.ConeGeometry(.11,.38,5),mat(0x9a7445,.5),group);crest.position.set(0,2.53,.02);crest.rotation.z=-.14;
	const weaponPivot=new THREE.Group();weaponPivot.position.set(.46,1.37,.05);group.add(weaponPivot);
	const grip=mesh(new THREE.CylinderGeometry(.045,.055,.32,6),mat(0x65452f),weaponPivot);grip.position.y=-.08;
	const guard=mesh(new THREE.BoxGeometry(.46,.075,.11),mat(0xa88a54,.4),weaponPivot);guard.position.set(0,-.25,.015);
	const blade=mesh(new THREE.BoxGeometry(.14,1.05,.045),mat(0xc6c8bf,.24),weaponPivot);blade.position.set(0,-.79,.02);player.weaponBlade=blade;
	const pommel=mesh(new THREE.SphereGeometry(.09,6,5),mat(0xc29a55,.35),weaponPivot);pommel.position.y=.13;
	group.position.set(0,0,4.6);player.mesh=group;player.weaponPivot=weaponPivot
}
function createEnemy(){
	const group=new THREE.Group();scene.add(group);
	const cape=mesh(new THREE.ConeGeometry(1.18,2.9,8),mat(0x241a1a),group);cape.position.set(0,1.35,-.38);cape.rotation.x=Math.PI;
	const body=mesh(new THREE.CapsuleGeometry(.77,1.45,6,10),mat(0x252a2b),group);body.position.y=1.52;
	const cuirass=mesh(new THREE.SphereGeometry(.82,12,9),mat(0x464c49,.4),group);cuirass.position.set(0,1.85,.28);cuirass.scale.set(1.04,.94,.62);
	const breastplate=mesh(new THREE.BoxGeometry(1.16,1.12,.24),mat(0x63645a,.34),group);breastplate.position.set(0,1.88,.68);
	const crest=mesh(new THREE.BoxGeometry(.14,1.36,.2),mat(0xa07847,.35),group);crest.position.set(0,1.86,.83);
	const belt=mesh(new THREE.BoxGeometry(1.42,.2,.92),mat(0x522f28),group);belt.position.set(0,1.06,0);
	for(const side of[-1,1]){
		const pauldron=mesh(new THREE.SphereGeometry(.5,9,7),mat(0x55564f,.4),group);pauldron.position.set(side*.82,2.36,.08);pauldron.scale.set(1.2,.72,1);
		for(let spike=0;spike<3;spike++){const point=mesh(new THREE.ConeGeometry(.12,.62,5),mat(0x8a7655,.4),group);point.position.set(side*(.62+spike*.22),2.72,.08);point.rotation.z=-side*.42}
		const arm=mesh(new THREE.CapsuleGeometry(.21,.65,5,7),mat(0x3d4342),group);arm.position.set(side*.86,1.66,.08);arm.rotation.z=-side*.16;
		const gauntlet=mesh(new THREE.BoxGeometry(.42,.4,.46),mat(0x77776a,.35),group);gauntlet.position.set(side*.94,1.2,.18);
		const greave=mesh(new THREE.BoxGeometry(.46,.9,.52),mat(0x3d4240,.45),group);greave.position.set(side*.34,.55,.05);
	}
	const helm=mesh(new THREE.SphereGeometry(.72,12,9),mat(0x444945,.28),group);helm.position.set(0,2.86,.06);helm.scale.set(1,.86,.92);
	const faceplate=mesh(new THREE.BoxGeometry(.83,.58,.22),mat(0x282d2c,.25),group);faceplate.position.set(0,2.76,.67);
	const visor=mesh(new THREE.BoxGeometry(.58,.1,.08),mat(0xff6337,.25,0xf44316),group);visor.position.set(0,2.9,.8);
	for(const side of[-1,1]){const horn=mesh(new THREE.ConeGeometry(.19,1.05,6),mat(0x9a7948,.42),group);horn.position.set(side*.57,3.53,.05);horn.rotation.z=-side*.52}
	const weaponPivot=new THREE.Group();weaponPivot.position.set(.9,1.65,.22);group.add(weaponPivot);
	const haft=mesh(new THREE.CylinderGeometry(.07,.11,3.25,8),mat(0x49352c),weaponPivot);haft.position.y=-.52;
	for(const y of[-1.45,-1.25,-1.05]){const wrap=mesh(new THREE.TorusGeometry(.105,.035,5,8),mat(0xa28458,.4),weaponPivot);wrap.position.set(0,y,0);wrap.rotation.x=Math.PI/2}
	const axeHead=mesh(new THREE.BoxGeometry(1.25,.88,.2),mat(0x777b73,.24),weaponPivot);axeHead.position.set(.55,.62,0);
	const axeEdge=mesh(new THREE.BoxGeometry(.14,.98,.24),mat(0x9a3f35,.3,0x37110e),weaponPivot);axeEdge.position.set(1.18,.62,0);
	const axeSpike=mesh(new THREE.ConeGeometry(.17,.58,5),mat(0x6a302b,.35),weaponPivot);axeSpike.position.set(-.28,.62,0);axeSpike.rotation.z=Math.PI/2;
	group.position.set(0,0,-43);enemy.mesh=group;enemy.weaponPivot=weaponPivot
}
function showToast(text){toastEl.textContent=text;toastEl.classList.remove("show");void toastEl.offsetWidth;toastEl.classList.add("show")}function resetGame(){player.health=100;player.stamina=100;player.souls=0;player.invulnerable=0;player.attacking=0;player.attackCooldown=0;player.roll=0;enemy.health=100;enemy.attackCooldown=1.6;enemy.telegraph=0;enemy.attacking=0;enemy.hurt=0;enemy.dead=false;player.mesh.position.set(0,0,4.6);enemy.mesh.position.set(0,0,-3.2);enemy.mesh.visible=true;enemy.mesh.rotation.set(0,Math.PI,0);messageScreen.classList.add("hidden");startScreen.classList.add("hidden");running=true;gameOver=false;showToast("THE WARDEN STIRS")}
function takeDamage(amount){if(player.invulnerable>0||gameOver)return;player.health=Math.max(0,player.health-amount);player.invulnerable=.55;flashEl.classList.remove("hit");void flashEl.offsetWidth;flashEl.classList.add("hit");if(player.health<=0)endGame(false)}function strike(){if(!running||gameOver||player.attackCooldown>0||player.roll>0||player.attacking>0)return;player.attacking=.38;player.attackCooldown=.56}function roll(){if(!running||player.stamina<27||player.roll>0||player.attacking>0)return;player.stamina-=27;player.roll=.52;player.invulnerable=.58}function endGame(won){gameOver=true;running=false;document.querySelector("#message-kicker").textContent=won?"THE LAST EMBER IS YOURS":"THE GATE REMEMBERS";document.querySelector("#message-title").textContent=won?"WARDEN SLAIN":"FALLEN";document.querySelector("#message-copy").textContent=won?"The ashen gate opens. The road beyond is yours to choose.":"The ash settles. Your ember can be reclaimed.";messageScreen.classList.remove("hidden")}
function updatePlayer(delta){if(player.invulnerable>0)player.invulnerable-=delta;if(player.attackCooldown>0)player.attackCooldown-=delta;if(hitStun>0)hitStun-=delta;if(player.roll>0){player.roll-=delta;const direction=new THREE.Vector3(0,0,1).applyAxisAngle(new THREE.Vector3(0,1,0),cameraYaw);player.mesh.position.addScaledVector(direction,delta*9);player.mesh.rotation.y=Math.atan2(direction.x,direction.z)}else if(hitStun<=0&&player.attacking<=0){const input=new THREE.Vector3((keys.KeyD?1:0)-(keys.KeyA?1:0),0,(keys.KeyS?1:0)-(keys.KeyW?1:0));if(input.lengthSq()){input.normalize().applyAxisAngle(new THREE.Vector3(0,1,0),cameraYaw);player.mesh.position.addScaledVector(input,delta*player.speed);player.mesh.rotation.y=Math.atan2(input.x,input.z)}}if(player.attacking>0){const previous=player.attacking;player.attacking-=delta;if(previous>.22&&player.attacking<=.22&&player.mesh.position.distanceTo(enemy.mesh.position)<2.35&&!enemy.dead){enemy.health=Math.max(0,enemy.health-26);player.souls+=26;showToast("A CLEAN STRIKE");if(enemy.health<=0){enemy.dead=true;player.souls+=974;setTimeout(()=>endGame(true),650)}}player.mesh.rotation.y+=delta*5}player.stamina=Math.min(100,player.stamina+delta*(player.roll>0?5:19));player.mesh.position.x=THREE.MathUtils.clamp(player.mesh.position.x,-arenaLimit,arenaLimit);player.mesh.position.z=THREE.MathUtils.clamp(player.mesh.position.z,-arenaLimit,arenaLimit)}
function updateEnemy(delta){if(enemy.dead){enemy.mesh.rotation.x+=delta*2;enemy.mesh.position.y=Math.max(-.5,enemy.mesh.position.y-delta*.9);return}enemy.attackCooldown-=delta;if(enemy.hurt>0)enemy.hurt-=delta;if(enemy.telegraph>0){enemy.telegraph-=delta;enemy.mesh.scale.setScalar(1+Math.sin(enemy.telegraph*22)*.025);if(enemy.telegraph<=0){enemy.attacking=.5;enemy.attackCooldown=1.5}}const distance=enemy.mesh.position.distanceTo(player.mesh.position),direction=player.mesh.position.clone().sub(enemy.mesh.position);direction.y=0;if(enemy.attacking>0){enemy.attacking-=delta;enemy.mesh.rotation.y+=delta*5;if(enemy.attacking<.25&&enemy.attacking+delta>=.25&&distance<2.5){takeDamage(28);hitStun=.2}}else if(enemy.telegraph<=0&&distance>2.2){direction.normalize();enemy.mesh.position.addScaledVector(direction,delta*1.25);enemy.mesh.rotation.y=Math.atan2(direction.x,direction.z)}else if(enemy.attackCooldown<=0&&distance<3.2){enemy.telegraph=.7;bossStateEl.textContent="ATTACKING";showToast("DODGE THE RED FLASH")}if(enemy.telegraph<=0&&enemy.attacking<=0)bossStateEl.textContent=enemy.health<40?"ENRAGED":"WATCHING";enemy.mesh.scale.setScalar(enemy.hurt>0?1.04:1);enemy.mesh.position.x=THREE.MathUtils.clamp(enemy.mesh.position.x,-arenaLimit,arenaLimit);enemy.mesh.position.z=THREE.MathUtils.clamp(enemy.mesh.position.z,-arenaLimit,arenaLimit)}
function updateCamera(delta){const target=player.mesh.position.clone();target.y+=1.25;const offset=new THREE.Vector3(Math.sin(cameraYaw)*8.2,4.1+cameraPitch,Math.cos(cameraYaw)*8.2);camera.position.lerp(target.clone().add(offset),1-Math.pow(.001,delta));camera.lookAt(target)}function updateHud(){healthEl.style.width=`${player.health}%`;staminaEl.style.width=`${player.stamina}%`;bossHealthEl.style.width=`${enemy.health}%`;document.querySelector("#souls").textContent=String(player.souls).padStart(4,"0")}function animate(){requestAnimationFrame(animate);const delta=Math.min(clock.getDelta(),.05);if(running&&!gameOver){updatePlayer(delta);updateEnemy(delta)}updateCamera(delta);updateHud();renderer.render(scene,camera)}
addEventListener("resize",()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});addEventListener("keydown",event=>{keys[event.code]=true;if(event.code==="Space"){event.preventDefault();roll()}});addEventListener("keyup",event=>{keys[event.code]=false});addEventListener("mousemove",event=>{if(document.pointerLockElement===canvas){cameraYaw-=event.movementX*.0025;cameraPitch=THREE.MathUtils.clamp(cameraPitch-event.movementY*.0015,-.05,1)}});canvas.addEventListener("mousedown",event=>{if(event.button===0)strike()});startButton.addEventListener("click",()=>{resetGame();canvas.requestPointerLock?.()});restartButton.addEventListener("click",()=>{resetGame();canvas.requestPointerLock?.()});canvas.addEventListener("click",()=>{if(running)canvas.requestPointerLock?.()});createWorld();createPlayer();createEnemy();renderer.setSize(innerWidth,innerHeight);camera.position.set(0,4,12);camera.lookAt(0,1,0);animate();
